version: '3'

services:

  db:
    image: mongo:4.4
    restart: unless-stopped
    container_name: db
    env_file: .env
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
        - ./data:/db
    networks:
      - app-network

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    env_file: .env
    environment:
      MONGO_URL: "mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@db:$MONGO_PORT/$MONGO_DB"
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - app-network
    command: ./wait-for.sh db:5432 -- /home/node/app/node_modules/.bin/nodemon bin/www

networks:
  app-network:
    driver: bridge
