version: '3'

services:

  db:
    image: mongo:4.4
    restart: always
    container_name: db
    environment:
      MONGO_INITDB_ROOT_USERNAME: datamola-admin
      MONGO_INITDB_ROOT_PASSWORD: datamola-pass
      MONGO_INITDB_DATABASE: chatDb
    volumes:
        - ./data:/db
    ports:
      - 5432:27017
  networks:
    - app-network

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    environment:
      MONGO_URL: "mongodb://datamola-admin:datamola-pass@db:5432/chatDb"
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - app-network
    command: ./wait-for.sh db:5432 -- /home/node/app/node_modules/.bin/nodemon bin/www

networks:
  app-network:
    driver: bridge
