version: '3.1'

services:

  db:
    image: mongo:4.4
    restart: unless-stopped
    container_name: db
    env_file: .env
    ports:
      - 27017:27017
    volumes:
        - ./data:/db
    networks:
      - app-network

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    env_file: .env
    environment:
      MONGO_URL: "mongodb://db:27017/$MONGO_DB"
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
