version: '3.1'

services:

  db:
    image: mongo
    restart: unless-stopped
    container_name: db
    env_file: .env
    ports:
      - 27017:27017
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_PASSWORD
    volumes:
        - ./data:/db
    networks:
      - app-network

  server:
    container_name: server
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - db
    env_file: .env
    environment:
      MONGO_URL: "mongodb://$MONGO_USERNAME:$MONGO_PASSWORD@db:$MONGO_PORT/$MONGO_DB"
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - app-network


networks:
  app-network:
    driver: bridge
